name: Continuous Intregration
on: push
env:
  DB_NAME: test
  DB_USER: root
  DB_PASSWORD: Raka#123
jobs:
  run_code_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Mysql
        run: |
          sudo /etc/init.d/mysql start
          sudo mysql -e 'ALTER USER "${{env.DB_USER}}"@"localhost" IDENTIFYED BY "${{$DB_PASSWORD}}";' -uroot -proot
          sudo mysql -e 'CREATE DATABASE ${{env.DB_NAME}};' -u${{env.DB_USER}} -u${{env.DB_PASSWORD}}
      - name: Checkot Repo Code
        uses: actions/checkout@v2
      - name: Set Up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Run linting
        run: |
          go fmt ./...
          go vet ./...
      - name: Run tests
        run: go test
