apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-resource
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  ingressClassName: nginx  
  tls:
    - hosts:
      - aifarming.tech
      - www.aifarming.tech
      secretName: letsencrypt-staging
  rules:
    - host: aifarming.tech
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: nginx-service
              port:
                number: 80
    - host: www.aifarming.tech
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: nginx-service
              port:
                number: 80
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: app
# spec:
#   selector:
#     app: app
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: app-deployment
#   labels:
#     app: app
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: app
#   template:
#     metadata:
#       labels:
#         app: app
#     spec:
#       containers:
#       - name: app
#         image: nginx:latest
#         ports:
#         - containerPort: 80
