FROM node:14-alpine as builder 

WORKDIR /app

COPY package.json .

RUN npm install

COPY  . .

RUN npm run build

# second stage 

FROM nginx:stable-alpine 

COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 80 

CMD [ "nginx" ,"-g","daemon off;" ]
