apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace : argocd 
spec: 
  project : default

  source:
    repoURL: http://gitlab.com/nanuchi/argocd-app-config.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
# 2) enable automatic  self healing 
# by defalut , changes made to the live cluster will not trigger automatic sync
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      prune: true # enable pruning (delete old resources)
      selfHeal: true # enable self healing