version: '3'

services:
  tidb:
    image: pingcap/tidb:latest
    container_name: tidb-server
    ports:
      - "4000:4000"  # TiDB server port
      - "10080:10080"  # TiDB status port
      - "2379:2379"    # TiKV server port
      - "9090:9090"    # PD server port
    # environment:
      #  - MYSQL_ROOT_PASSWORD=your_password

